name: 🚩 Bugs, Errors, and Other Issues
description: Report an issue to help us improve FF Ultima.
labels:
  - "bug"
  - "issue"
body:
  - type: markdown
    attributes:
      value: |
        ### Before submitting, Please fill out the checklist.

  - type: checkboxes
    id: confirmations
    attributes:
      label: "My Checklist:"
      description: "![image](https://github.com/user-attachments/assets/7c3c1fb9-8080-4823-9994-23e6af91498e) <br> First time install? If you don't see this ↑ welcome message on your about:config page, follow the install guide [Steps 4-7](https://github.com/soulhotel/FF-ULTIMA/wiki/How-to-Install-the-Theme#installation)"
      options:
        - label: "I've looked at the [FF Ultima Wiki](https://ff-ultima.github.io/docs/getting-started)."
          required: true
        - label: "🟠 My Browser is Firefox (Default)."
        - label: "🟣 My Browser is Firefox (Nightly)."
        - label: "🔵 My Browser is Firefox (Beta/Developer)."
        - label: "⚪ My Browser is Librewolf (fork)."
        - label: "My OS (operating system) is Windows."
        - label: "My OS (operating system) is Linux."
        - label: "My OS (operating system) is Mac."
        - label: "My Browser is on the latest version."

  - type: textarea
    id: issue-description
    attributes:
      label: "The Issue:"
      description: "A detailed description of the issue. Or what you expect to happen."
      placeholder: "A detailed description of the issue. Or what you expect to happen."
    validations:
      required: true

  - type: textarea
    id: picture-video
    attributes:
      label: "Picture/Video of the Issue:"
      description: "Screenshot(s) or video of the issue are preferred."
      placeholder: "Drag & Drop | Copy & Paste | or Link to Picture & Video"
    validations:
      required: false
